name: Deploy to DO and DO Spaces
on:
  push:
    branches: [ master ]

  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@main
        with:
          fetch-depth: 0
          
      - name: Base Deployment via SSH
        uses: appleboy/ssh-action@v0.1.4
        id: deployment
        with:
         host: ${{secrets.SSH_HOST}}
         key: ${{secrets.SSH_KEY}}
         username: ${{secrets.SSH_USERNAME}}
         script_stop: true                
         script: |
          /var/sites/music.keyjayhd.com/deploy.sh
          echo 'Base deployment successful to Digital Ocean'
          
      #- name: Upload to KJ Data Store
      #  uses: BetaHuhn/do-spaces-action@v2
      #  id: spaces
      #  with:
      #    access_key: ${{ secrets.DO_ACCESS_KEY}}
      #    secret_key: ${{ secrets.DO_SECRET_KEY }}
      #    space_name: ${{ secrets.DO_SPACE_NAME }}
      #    space_region: ${{ secrets.DO_SPACE_REGION }}
      #    source: public

      - name: Upload to KJO Music Data Store and Sync
       # uses: laukstein/do-spaces@main
       # env:
       #   DO_TOKEN: ${{ secrets.DO_TOKEN }}
       #   DO_ACCESS: ${{ secrets.DO_ACCESS_KEY }}
       #   DO_SECRET: ${{ secrets.DO_SECRET_KEY }}
       #   DO_NAME: ${{ secrets.DO_SPACE_NAME }}
       #   DO_REGION: ${{ secrets.DO_SPACE_REGION }}
       #   DO_DIR: public
       #   LOCAL_DIR: public
        
        uses: play-curious/do-space-sync-action@master
        with:
         args: --acl public-read
        env:
         SOURCE_DIR: public
         DEST_DIR: public
         SPACE_NAME: ${{ secrets.DO_SPACE_NAME }}
         SPACE_REGION: ${{ secrets.DO_SPACE_REGION }}
         SPACE_ACCESS_KEY_ID: ${{ secrets.DO_ACCESS_KEY }}
         SPACE_SECRET_ACCESS_KEY: ${{ secrets.DO_SECRET_KEY }}
